### ISSUE TITLE
 Module build failed: ReferenceError: /home/zafar/projects/meteor-webpack-react-kickstart/react/index.jsx: Symbol is not defined

### ISSUE THREAD

**Issue by ansarizafar** [thereactivestack/meteor-webpack-react-kickstart#5]
I am getting this error
````
zafar@home:~/projects/meteor-webpack-react-kickstart$ ./scripts/run-dev.sh
npm WARN package.json meteor-webpack-react-kickstart@0.1.0 No repository field.
npm WARN package.json meteor-webpack-react-kickstart@0.1.0 No license field.
[[[[[ ~/projects/meteor-webpack-react-kickstart/meteor ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/
I20150924-11:22:04.439(5)? webpack built 2b225a84569385567fcf in 1269ms
I20150924-11:22:04.439(5)? Hash: 2b225a84569385567fcf
I20150924-11:22:04.439(5)? Version: webpack 1.12.1
I20150924-11:22:04.439(5)? Time: 1269ms
I20150924-11:22:04.440(5)?  Asset     Size  Chunks       Chunk Names
I20150924-11:22:04.440(5)? app.js  29.7 kB       0       main
I20150924-11:22:04.440(5)? chunk    {0} app.js (main) 6.62 kB [rendered]
I20150924-11:22:04.440(5)?     [0] multi main 40 bytes {0} [built] [1 error]
I20150924-11:22:04.440(5)?     [1] /home/zafar/projects/meteor-webpack-react-kickstart/~/webpack-hot-middleware/client.js 2.6 kB {0} [built]
I20150924-11:22:04.440(5)?     [2] /home/zafar/projects/meteor-webpack-react-kickstart/~/webpack-hot-middleware/~/strip-ansi/index.js 161 bytes {0} [built]
I20150924-11:22:04.440(5)?     [3] /home/zafar/projects/meteor-webpack-react-kickstart/~/webpack-hot-middleware/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0} [built]
I20150924-11:22:04.441(5)?     [4] /home/zafar/projects/meteor-webpack-react-kickstart/~/webpack-hot-middleware/client-overlay.js 917 bytes {0} [built]
I20150924-11:22:04.441(5)?     [5] /home/zafar/projects/meteor-webpack-react-kickstart/~/webpack-hot-middleware/processUpdate.js 2.75 kB {0} [built]
I20150924-11:22:04.441(5)? 
I20150924-11:22:04.441(5)? ERROR in /home/zafar/projects/meteor-webpack-react-kickstart/react/index.jsx
I20150924-11:22:04.441(5)? Module build failed: ReferenceError: /home/zafar/projects/meteor-webpack-react-kickstart/react/index.jsx: Symbol is not defined
I20150924-11:22:04.441(5)?     at buildIsCreateClassCallExpression (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-plugin-react-transform/lib/index.js:65:43)
I20150924-11:22:04.441(5)?     at NodePath.enter (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-plugin-react-transform/lib/index.js:346:42)
I20150924-11:22:04.442(5)?     at NodePath.call (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/path/context.js:56:28)
I20150924-11:22:04.442(5)?     at NodePath.visit (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/path/context.js:90:8)
I20150924-11:22:04.442(5)?     at TraversalContext.visitSingle (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/context.js:132:12)
I20150924-11:22:04.442(5)?     at TraversalContext.visit (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/context.js:148:19)
I20150924-11:22:04.442(5)?     at Function.traverse.node (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/index.js:76:17)
I20150924-11:22:04.442(5)?     at Object.traverse [as default] (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/traversal/index.js:55:14)
I20150924-11:22:04.442(5)?     at PluginPass.transform (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/transformation/plugin-pass.js:51:27)
I20150924-11:22:04.442(5)?     at File.transform (/home/zafar/projects/meteor-webpack-react-kickstart/node_modules/babel-core/lib/transformation/file/index.js:621:12)
I20150924-11:22:04.443(5)?  @ multi main
W20150924-11:22:04.433(5)? (STDERR) Warning: you are using an outdated format of React Transform configuration. Please update your configuration to the new format. See the Releases page for migration instructions: https://github.com/gaearon/babel-plugin-react-transform/releases

````

**Comment by eXon** [comment]
This should be fixed. It was missing the ecmascript package on the Meteor project.
